<?php

declare(strict_types=1);

use yii\db\Migration;

final class m210423_084505_region extends Migration
{
    public function safeUp()
    {
        $this->createTable('{{%region}}', [
            'id' => $this->char(2)->notNull()->check(vsprintf('[[id]] ~ %s', [
                $this->db->quoteValue('^[a-z]{2}$'),
            ])),
            'name_ja' => $this->string()->notNull(),
            'name_en' => $this->string()->notNull(),
            'PRIMARY KEY ([[id]])',
        ]);

        $this->batchInsert('{{%region}}', ['id', 'name_ja', 'name_en'], [
            ['ad', 'アンドラ', 'Andorra'],
            ['ae', 'アラブ首長国連邦', 'United Arab Emirates'],
            ['af', 'アフガニスタン', 'Afghanistan'],
            ['ag', 'アンティグア・バーブーダ', 'Antigua and Barbuda'],
            ['ai', 'アンギラ', 'Anguilla'],
            ['al', 'アルバニア', 'Albania'],
            ['am', 'アルメニア', 'Armenia'],
            ['ao', 'アンゴラ', 'Angola'],
            ['ap', 'アジア太平洋地域', 'Asia Pacific'],
            ['aq', '南極', 'Antarctica'],
            ['ar', 'アルゼンチン', 'Argentina'],
            ['as', 'アメリカ領サモア', 'American Samoa'],
            ['at', 'オーストリア', 'Austria'],
            ['au', 'オーストラリア', 'Australia'],
            ['aw', 'アルバ', 'Aruba'],
            ['ax', 'オーランド諸島', 'Åland Islands'],
            ['az', 'アゼルバイジャン', 'Azerbaijan'],
            ['ba', 'ボスニア・ヘルツェゴビナ', 'Bosnia and Herzegovina'],
            ['bb', 'バルバドス', 'Barbados'],
            ['bd', 'バングラデシュ', 'Bangladesh'],
            ['be', 'ベルギー', 'Belgium'],
            ['bf', 'ブルキナファソ', 'Burkina Faso'],
            ['bg', 'ブルガリア', 'Bulgaria'],
            ['bh', 'バーレーン', 'Bahrain'],
            ['bi', 'ブルンジ', 'Burundi'],
            ['bj', 'ベナン', 'Benin'],
            ['bl', 'サン・バルテルミー', 'Saint Barthélemy'],
            ['bm', 'バミューダ', 'Bermuda'],
            ['bn', 'ブルネイ・ダルサラーム', 'Brunei Darussalam'],
            ['bo', 'ボリビア多民族国', 'Bolivia, Plurinational State of'],
            ['bq', 'ボネール、シント・ユースタティウスおよびサバ', 'Bonaire, Saint Eustatius and Saba'],
            ['br', 'ブラジル', 'Brazil'],
            ['bs', 'バハマ', 'Bahamas'],
            ['bt', 'ブータン', 'Bhutan'],
            ['bv', 'ブーベ島', 'Bouvet Island'],
            ['bw', 'ボツワナ', 'Botswana'],
            ['by', 'ベラルーシ', 'Belarus'],
            ['bz', 'ベリーズ', 'Belize'],
            ['ca', 'カナダ', 'Canada'],
            ['cc', 'ココス（キーリング）諸島', 'Cocos (Keeling) Islands'],
            ['cd', 'コンゴ民主共和国', 'Congo, the Democratic Republic of the'],
            ['cf', '中央アフリカ共和国', 'Central African Republic'],
            ['cg', 'コンゴ共和国', 'Congo'],
            ['ch', 'スイス', 'Switzerland'],
            ['ci', 'コートジボワール', 'Côte d\'Ivoire'],
            ['ck', 'クック諸島', 'Cook Islands'],
            ['cl', 'チリ', 'Chile'],
            ['cm', 'カメルーン', 'Cameroon'],
            ['cn', '中華人民共和国', 'China'],
            ['co', 'コロンビア', 'Colombia'],
            ['cr', 'コスタリカ', 'Costa Rica'],
            ['cu', 'キューバ', 'Cuba'],
            ['cv', 'カーボベルデ', 'Cape Verde'],
            ['cw', 'キュラソー', 'Curaçao'],
            ['cx', 'クリスマス島', 'Christmas Island'],
            ['cy', 'キプロス', 'Cyprus'],
            ['cz', 'チェコ', 'Czech Republic'],
            ['de', 'ドイツ', 'Germany'],
            ['dj', 'ジブチ', 'Djibouti'],
            ['dk', 'デンマーク', 'Denmark'],
            ['dm', 'ドミニカ国', 'Dominica'],
            ['do', 'ドミニカ共和国', 'Dominican Republic'],
            ['dz', 'アルジェリア', 'Algeria'],
            ['ec', 'エクアドル', 'Ecuador'],
            ['ee', 'エストニア', 'Estonia'],
            ['eg', 'エジプト', 'Egypt'],
            ['eh', '西サハラ', 'Western Sahara'],
            ['er', 'エリトリア', 'Eritrea'],
            ['es', 'スペイン', 'Spain'],
            ['et', 'エチオピア', 'Ethiopia'],
            ['eu', '欧州連合', 'European Union'],
            ['fi', 'フィンランド', 'Finland'],
            ['fj', 'フィジー', 'Fiji'],
            ['fk', 'フォークランド（マルビナス）諸島', 'Falkland Islands (Malvinas)'],
            ['fm', 'ミクロネシア連邦', 'Micronesia, Federated States of'],
            ['fo', 'フェロー諸島', 'Faroe Islands'],
            ['fr', 'フランス', 'France'],
            ['ga', 'ガボン', 'Gabon'],
            ['gb', 'イギリス', 'United Kingdom'],
            ['gd', 'グレナダ', 'Grenada'],
            ['ge', 'ジョージア', 'Georgia'],
            ['gf', 'フランス領ギアナ', 'French Guiana'],
            ['gg', 'ガーンジー', 'Guernsey'],
            ['gh', 'ガーナ', 'Ghana'],
            ['gi', 'ジブラルタル', 'Gibraltar'],
            ['gl', 'グリーンランド', 'Greenland'],
            ['gm', 'ガンビア', 'Gambia'],
            ['gn', 'ギニア', 'Guinea'],
            ['gp', 'グアドループ', 'Guadeloupe'],
            ['gq', '赤道ギニア', 'Equatorial Guinea'],
            ['gr', 'ギリシャ', 'Greece'],
            ['gs', 'サウスジョージア・サウスサンドウィッチ諸島', 'South Georgia and the South Sandwich Islands'],
            ['gt', 'グアテマラ', 'Guatemala'],
            ['gu', 'グアム', 'Guam'],
            ['gw', 'ギニアビサウ', 'Guinea-Bissau'],
            ['gy', 'ガイアナ', 'Guyana'],
            ['hk', '香港', 'Hong Kong'],
            ['hm', 'ハード島とマクドナルド諸島', 'Heard Island and McDonald Islands'],
            ['hn', 'ホンジュラス', 'Honduras'],
            ['hr', 'クロアチア', 'Croatia'],
            ['ht', 'ハイチ', 'Haiti'],
            ['hu', 'ハンガリー', 'Hungary'],
            ['id', 'インドネシア', 'Indonesia'],
            ['ie', 'アイルランド', 'Ireland'],
            ['il', 'イスラエル', 'Israel'],
            ['im', 'マン島', 'Isle of Man'],
            ['in', 'インド', 'India'],
            ['io', 'イギリス領インド洋地域', 'British Indian Ocean Territory'],
            ['iq', 'イラク', 'Iraq'],
            ['ir', 'イラン・イスラム共和国', 'Iran, Islamic Republic of'],
            ['is', 'アイスランド', 'Iceland'],
            ['it', 'イタリア', 'Italy'],
            ['je', 'ジャージー', 'Jersey'],
            ['jm', 'ジャマイカ', 'Jamaica'],
            ['jo', 'ヨルダン', 'Jordan'],
            ['jp', '日本', 'Japan'],
            ['ke', 'ケニア', 'Kenya'],
            ['kg', 'キルギス', 'Kyrgyzstan'],
            ['kh', 'カンボジア', 'Cambodia'],
            ['ki', 'キリバス', 'Kiribati'],
            ['km', 'コモロ', 'Comoros'],
            ['kn', 'セントクリストファー・ネイビス', 'Saint Kitts and Nevis'],
            ['kp', '朝鮮民主主義人民共和国', 'Korea, Democratic People\'s Republic of'],
            ['kr', '大韓民国', 'Korea, Republic of'],
            ['kw', 'クウェート', 'Kuwait'],
            ['ky', 'ケイマン諸島', 'Cayman Islands'],
            ['kz', 'カザフスタン', 'Kazakhstan'],
            ['la', 'ラオス人民民主共和国', 'Lao People\'s Democratic Republic'],
            ['lb', 'レバノン', 'Lebanon'],
            ['lc', 'セントルシア', 'Saint Lucia'],
            ['li', 'リヒテンシュタイン', 'Liechtenstein'],
            ['lk', 'スリランカ', 'Sri Lanka'],
            ['lr', 'リベリア', 'Liberia'],
            ['ls', 'レソト', 'Lesotho'],
            ['lt', 'リトアニア', 'Lithuania'],
            ['lu', 'ルクセンブルク', 'Luxembourg'],
            ['lv', 'ラトビア', 'Latvia'],
            ['ly', 'リビア', 'Libya'],
            ['ma', 'モロッコ', 'Morocco'],
            ['mc', 'モナコ', 'Monaco'],
            ['md', 'モルドバ共和国', 'Moldova, Republic of'],
            ['me', 'モンテネグロ', 'Montenegro'],
            ['mf', 'サン・マルタン（フランス領）', 'Saint Martin (French part)'],
            ['mg', 'マダガスカル', 'Madagascar'],
            ['mh', 'マーシャル諸島', 'Marshall Islands'],
            ['mk', 'マケドニア旧ユーゴスラビア共和国', 'Macedonia, the former Yugoslav Republic of'],
            ['ml', 'マリ', 'Mali'],
            ['mm', 'ミャンマー', 'Myanmar'],
            ['mn', 'モンゴル', 'Mongolia'],
            ['mo', 'マカオ', 'Macao'],
            ['mp', '北マリアナ諸島', 'Northern Mariana Islands'],
            ['mq', 'マルティニーク', 'Martinique'],
            ['mr', 'モーリタニア', 'Mauritania'],
            ['ms', 'モントセラト', 'Montserrat'],
            ['mt', 'マルタ', 'Malta'],
            ['mu', 'モーリシャス', 'Mauritius'],
            ['mv', 'モルディブ', 'Maldives'],
            ['mw', 'マラウイ', 'Malawi'],
            ['mx', 'メキシコ', 'Mexico'],
            ['my', 'マレーシア', 'Malaysia'],
            ['mz', 'モザンビーク', 'Mozambique'],
            ['na', 'ナミビア', 'Namibia'],
            ['nc', 'ニューカレドニア', 'New Caledonia'],
            ['ne', 'ニジェール', 'Niger'],
            ['nf', 'ノーフォーク島', 'Norfolk Island'],
            ['ng', 'ナイジェリア', 'Nigeria'],
            ['ni', 'ニカラグア', 'Nicaragua'],
            ['nl', 'オランダ', 'Netherlands'],
            ['no', 'ノルウェー', 'Norway'],
            ['np', 'ネパール', 'Nepal'],
            ['nr', 'ナウル', 'Nauru'],
            ['nu', 'ニウエ', 'Niue'],
            ['nz', 'ニュージーランド', 'New Zealand'],
            ['om', 'オマーン', 'Oman'],
            ['pa', 'パナマ', 'Panama'],
            ['pe', 'ペルー', 'Peru'],
            ['pf', 'フランス領ポリネシア', 'French Polynesia'],
            ['pg', 'パプアニューギニア', 'Papua New Guinea'],
            ['ph', 'フィリピン', 'Philippines'],
            ['pk', 'パキスタン', 'Pakistan'],
            ['pl', 'ポーランド', 'Poland'],
            ['pm', 'サンピエール島・ミクロン島', 'Saint Pierre and Miquelon'],
            ['pn', 'ピトケアン', 'Pitcairn'],
            ['pr', 'プエルトリコ', 'Puerto Rico'],
            ['ps', 'パレスチナ', 'Palestinian Territory, Occupied'],
            ['pt', 'ポルトガル', 'Portugal'],
            ['pw', 'パラオ', 'Palau'],
            ['py', 'パラグアイ', 'Paraguay'],
            ['qa', 'カタール', 'Qatar'],
            ['re', 'レユニオン', 'Réunion'],
            ['ro', 'ルーマニア', 'Romania'],
            ['rs', 'セルビア', 'Serbia'],
            ['ru', 'ロシア連邦', 'Russian Federation'],
            ['rw', 'ルワンダ', 'Rwanda'],
            ['sa', 'サウジアラビア', 'Saudi Arabia'],
            ['sb', 'ソロモン諸島', 'Solomon Islands'],
            ['sc', 'セーシェル', 'Seychelles'],
            ['sd', 'スーダン', 'Sudan'],
            ['se', 'スウェーデン', 'Sweden'],
            ['sg', 'シンガポール', 'Singapore'],
            ['sh', 'セントヘレナ・アセンションおよびトリスタンダクーニャ', 'Saint Helena, Ascension and Tristan da Cunha'],
            ['si', 'スロベニア', 'Slovenia'],
            ['sj', 'スヴァールバル諸島およびヤンマイエン島', 'Svalbard and Jan Mayen'],
            ['sk', 'スロバキア', 'Slovakia'],
            ['sl', 'シエラレオネ', 'Sierra Leone'],
            ['sm', 'サンマリノ', 'San Marino'],
            ['sn', 'セネガル', 'Senegal'],
            ['so', 'ソマリア', 'Somalia'],
            ['sr', 'スリナム', 'Suriname'],
            ['ss', '南スーダン', 'South Sudan'],
            ['st', 'サントメ・プリンシペ', 'Sao Tome and Principe'],
            ['sv', 'エルサルバドル', 'El Salvador'],
            ['sx', 'シント・マールテン（オランダ領）', 'Sint Maarten (Dutch part)'],
            ['sy', 'シリア・アラブ共和国', 'Syrian Arab Republic'],
            ['sz', 'スワジランド', 'Swaziland'],
            ['tc', 'タークス・カイコス諸島', 'Turks and Caicos Islands'],
            ['td', 'チャド', 'Chad'],
            ['tf', 'フランス領南方・南極地域', 'French Southern Territories'],
            ['tg', 'トーゴ', 'Togo'],
            ['th', 'タイ', 'Thailand'],
            ['tj', 'タジキスタン', 'Tajikistan'],
            ['tk', 'トケラウ', 'Tokelau'],
            ['tl', '東ティモール', 'Timor-Leste'],
            ['tm', 'トルクメニスタン', 'Turkmenistan'],
            ['tn', 'チュニジア', 'Tunisia'],
            ['to', 'トンガ', 'Tonga'],
            ['tr', 'トルコ', 'Turkey'],
            ['tt', 'トリニダード・トバゴ', 'Trinidad and Tobago'],
            ['tv', 'ツバル', 'Tuvalu'],
            ['tw', '台湾', 'Taiwan'],
            ['tz', 'タンザニア', 'Tanzania, United Republic of'],
            ['ua', 'ウクライナ', 'Ukraine'],
            ['ug', 'ウガンダ', 'Uganda'],
            ['um', '合衆国領有小離島', 'United States Minor Outlying Islands'],
            ['us', 'アメリカ合衆国', 'United States'],
            ['uy', 'ウルグアイ', 'Uruguay'],
            ['uz', 'ウズベキスタン', 'Uzbekistan'],
            ['va', 'バチカン市国', 'Holy See (Vatican City State)'],
            ['vc', 'セントビンセントおよびグレナディーン諸島', 'Saint Vincent and the Grenadines'],
            ['ve', 'ベネズエラ・ボリバル共和国', 'Venezuela, Bolivarian Republic of'],
            ['vg', 'イギリス領ヴァージン諸島', 'Virgin Islands, British'],
            ['vi', 'アメリカ領ヴァージン諸島', 'Virgin Islands, U.S.'],
            ['vn', 'ベトナム', 'Viet Nam'],
            ['vu', 'バヌアツ', 'Vanuatu'],
            ['wf', 'ウォリス・フツナ', 'Wallis and Futuna'],
            ['ws', 'サモア', 'Samoa'],
            ['ye', 'イエメン', 'Yemen'],
            ['yt', 'マヨット', 'Mayotte'],
            ['za', '南アフリカ', 'South Africa'],
            ['zm', 'ザンビア', 'Zambia'],
            ['zw', 'ジンバブエ', 'Zimbabwe'],
        ]);
        return true;
    }

    public function safeDown()
    {
        $this->dropTable('{{%region}}');
        return true;
    }
}
